version: '3.5'

services:
  backend:
    image: docker_back
    build: ./backend
    ports: 
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=user
      - DB_PASSWORD=pass
      - DB_NAME=database
      - DB_HOST=postgres
    
  frontend:
    image: docker_front
    build: ./frontend
    ports:
      - 5000:5000

  redis:
    image: redis
  
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=database
