version: '3.5'

services:
    training:
      image: training
      build: ./ml-kurkkumopo-training
      volumes:
        - imgs:/src/imgs
        - model:/src/model
    backend:
      image: backend
      build: ./ml-kurkkumopo-backend
      ports: 
        - 5000:5000
      volumes:
        - model:/src/model
    frontend:
      image: frontend
      build: ./ml-kurkkumopo-frontend
      ports:
        - 3000:3000
      volumes:
        - model:/usr/src/app/model
      environment:
        - API_URL=http://localhoct:5000

volumes:
  model:
  imgs:
