version: '3.5'

services:
  backend:
    image: docker_back
    build: ./backend
    ports: 
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
    
  frontend:
    image: docker_front
    build: ./frontend
    ports:
      - 5000:5000

  redis:
    image: redis
